Adiciona o crud de respostas
Ask-UFCG/projeto-novo-back pull request #12
Opened 2021-07-24 20:30 UTC by wellissongomes

2021-07-25 16:47 UTC, victorbrandaoa requested changes

2021-07-25 16:47 UTC, victorbrandaoa commented on ufcg/src/main/java/br/com/askufcg/dtos/answer/AnswerMapper.java
> +                .comments(new ArrayList<>())
Quando usa esse método no update os comentários da resposta atualizada não são apagados? Porque ta sendo criado um novo ArrayList vazio.

2021-07-25 16:47 UTC, victorbrandaoa commented on ufcg/src/main/java/br/com/askufcg/services/answer/AnswerServiceImpl.java
> +        answerToUpdate.setComments(answer.getComments());
Aqui aquilo que mencionei acima, quando setar os comentários, não vai apagar os que já tiverem (se tiver algum)? Já que após passar no método toAnswer do AnswerMapper os comentários são criados como um novo ArrayList vazio.

2021-07-25 17:48 UTC, wellissongomes commented on ufcg/src/main/java/br/com/askufcg/dtos/answer/AnswerMapper.java
> +                .comments(new ArrayList<>())
Na hora da criação de uma resposta não há comentários, ou seja, uma lista vazia.

2021-07-25 17:49 UTC, wellissongomes commented on ufcg/src/main/java/br/com/askufcg/services/answer/AnswerServiceImpl.java
> +        answerToUpdate.setComments(answer.getComments());
Bem observado. O dto deveria ser especifico para o POST e outro para o PUT.

2021-07-25 17:58 UTC, wellissongomes commented on ufcg/src/main/java/br/com/askufcg/services/answer/AnswerServiceImpl.java
> +        answerToUpdate.setComments(answer.getComments());
Vendo agora, nem deveria ter esse

`answerToUpdate.setComments(answer.getComments());
`

Visto que essa parte de adicionar/remover um comentário está em outro local.

2021-07-25 18:07 UTC, victorbrandaoa approved these changes

2021-07-25 18:09 UTC, victorbrandaoa commented
Pessoal, eu revisei e aprovei, não fiz o merge para que mais alguém possa olha e talvez ver algo que eu não tenha notado.

2021-07-28 13:02 UTC, ericdmg approved these changes

2021-07-28 13:05 UTC, merged