Adicionando rota de busca por perguntas
Ask-UFCG/projeto-novo-back pull request #18
Opened 2021-08-02 18:24 UTC by wellissongomes

Há 4 formas de realizar uma busca:

1. `API_URL/search` (sem passar nada)
2. `API_URL/search?title="algum titulo"`
3. `API_URL/search?tags=tagA,tagB,tagC"`
4. `API_URL/search?title="algum titulo"&tags="tagA,tagB,tagC"`

2021-08-02 18:40 UTC, wellissongomes commented
Esqueci de fazer a parte dos filtros.. :smile: depois eu faço

2021-08-02 20:00 UTC, victorbrandaoa commented
Ta ótimo, quando tiver a parte dos filtros a revisão será finalizada e o PR aceito.

2021-08-04 00:58 UTC, wellissongomes commented
Além das possibilidades de busca citadas acima, também é válido:

1. `API_URL/search?filter=vote` (retorna as com mais likes)
2. `API_URL/search?filter=relevant` (retorna as mais relevantes)
3. `API_URL/search?filter=answered` (retorna apenas as que foram marcadas como respondidas)

2021-08-04 14:02 UTC, victorbrandaoa requested changes

2021-08-04 14:02 UTC, victorbrandaoa commented on ufcg/src/main/java/br/com/askufcg/services/search/QuestionSearchServiceImpl.java
> +        newQuestions.sort(byLike);
Porque faz o .sort() duas vezes aqui?

2021-08-04 14:02 UTC, victorbrandaoa commented on ufcg/src/main/java/br/com/askufcg/services/search/QuestionSearchServiceImpl.java
> +        Collections.reverse(questions);
Porque usa o .reverse()?

2021-08-04 14:02 UTC, victorbrandaoa commented on ufcg/src/main/java/br/com/askufcg/services/search/QuestionSearchServiceImpl.java
> +                                .filter(question -> question.getTags().stream().anyMatch(tags::contains))
Esses :: ali no anyMatch() faz o que?

2021-08-04 14:02 UTC, victorbrandaoa commented on ufcg/src/main/java/br/com/askufcg/dtos/question/QuestionMapper.java
> +                .answered(question.isAnswered())
Esse método isAnswerd() não está explícitamente definido no model Question, o Spring define ele?

2021-08-04 14:12 UTC, wellissongomes commented on ufcg/src/main/java/br/com/askufcg/services/search/QuestionSearchServiceImpl.java
> +        newQuestions.sort(byLike);
Foi porque eu tava usando na referência original e esqueci de apagar.

2021-08-04 14:12 UTC, wellissongomes commented on ufcg/src/main/java/br/com/askufcg/services/search/QuestionSearchServiceImpl.java
> +        Collections.reverse(questions);
Por padrão será exibido as questões mais novas para as mais antigas, ou seja, basta inverter a ordem dos elementos já que a lista mantém a ordem quando adicionamos algum elemento.

2021-08-04 14:17 UTC, wellissongomes commented on ufcg/src/main/java/br/com/askufcg/services/search/QuestionSearchServiceImpl.java
> +                                .filter(question -> question.getTags().stream().anyMatch(tags::contains))
No lugar de eu fazer ```tags -> tags.contains(tag)```, basta fazer` tags::contains` já que ele está retornando a função contains que recebe uma tag como parâmetro. Isso apenas simplifica o uso de funções de alta ordem.

2021-08-04 14:18 UTC, wellissongomes commented on ufcg/src/main/java/br/com/askufcg/dtos/question/QuestionMapper.java
> +                .answered(question.isAnswered())
Isso é definido pelo lombok. É o mesmo que getAnswered, só que mais claro.

2021-08-04 14:23 UTC, victorbrandaoa approved these changes

2021-08-04 14:24 UTC, merged